# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\elektroNIK\Desktop\P3DA\software\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_light = QtWidgets.QWidget()
        self.tab_light.setObjectName("tab_light")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_light)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_color_bright = QtWidgets.QGroupBox(self.tab_light)
        self.groupBox_color_bright.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_color_bright.sizePolicy().hasHeightForWidth())
        self.groupBox_color_bright.setSizePolicy(sizePolicy)
        self.groupBox_color_bright.setObjectName("groupBox_color_bright")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_color_bright)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalSlider_b = QtWidgets.QSlider(self.groupBox_color_bright)
        self.horizontalSlider_b.setEnabled(True)
        self.horizontalSlider_b.setMaximum(255)
        self.horizontalSlider_b.setProperty("value", 0)
        self.horizontalSlider_b.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_b.setObjectName("horizontalSlider_b")
        self.gridLayout_3.addWidget(self.horizontalSlider_b, 3, 3, 2, 1)
        self.horizontalSlider_g = QtWidgets.QSlider(self.groupBox_color_bright)
        self.horizontalSlider_g.setEnabled(True)
        self.horizontalSlider_g.setMaximum(255)
        self.horizontalSlider_g.setProperty("value", 0)
        self.horizontalSlider_g.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_g.setObjectName("horizontalSlider_g")
        self.gridLayout_3.addWidget(self.horizontalSlider_g, 2, 3, 1, 1)
        self.spinBox_b = QtWidgets.QSpinBox(self.groupBox_color_bright)
        self.spinBox_b.setEnabled(True)
        self.spinBox_b.setWrapping(False)
        self.spinBox_b.setFrame(True)
        self.spinBox_b.setReadOnly(False)
        self.spinBox_b.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_b.setAccelerated(False)
        self.spinBox_b.setProperty("showGroupSeparator", False)
        self.spinBox_b.setMaximum(255)
        self.spinBox_b.setProperty("value", 0)
        self.spinBox_b.setObjectName("spinBox_b")
        self.gridLayout_3.addWidget(self.spinBox_b, 3, 4, 2, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_color_bright)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 2, 1, 1)
        self.spinBox_g = QtWidgets.QSpinBox(self.groupBox_color_bright)
        self.spinBox_g.setEnabled(True)
        self.spinBox_g.setWrapping(False)
        self.spinBox_g.setFrame(True)
        self.spinBox_g.setReadOnly(False)
        self.spinBox_g.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_g.setAccelerated(False)
        self.spinBox_g.setProperty("showGroupSeparator", False)
        self.spinBox_g.setMaximum(255)
        self.spinBox_g.setProperty("value", 0)
        self.spinBox_g.setObjectName("spinBox_g")
        self.gridLayout_3.addWidget(self.spinBox_g, 2, 4, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_color_bright)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 2, 2, 1)
        self.spinBox_r = QtWidgets.QSpinBox(self.groupBox_color_bright)
        self.spinBox_r.setEnabled(True)
        self.spinBox_r.setWrapping(False)
        self.spinBox_r.setFrame(True)
        self.spinBox_r.setReadOnly(False)
        self.spinBox_r.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_r.setAccelerated(False)
        self.spinBox_r.setProperty("showGroupSeparator", False)
        self.spinBox_r.setMaximum(255)
        self.spinBox_r.setProperty("value", 0)
        self.spinBox_r.setObjectName("spinBox_r")
        self.gridLayout_3.addWidget(self.spinBox_r, 0, 4, 2, 2)
        self.label = QtWidgets.QLabel(self.groupBox_color_bright)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 2, 2, 1)
        self.lcdNumber_bright = QtWidgets.QLCDNumber(self.groupBox_color_bright)
        self.lcdNumber_bright.setEnabled(True)
        self.lcdNumber_bright.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_bright.setSmallDecimalPoint(False)
        self.lcdNumber_bright.setDigitCount(3)
        self.lcdNumber_bright.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_bright.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_bright.setProperty("value", 0.0)
        self.lcdNumber_bright.setProperty("intValue", 0)
        self.lcdNumber_bright.setObjectName("lcdNumber_bright")
        self.gridLayout_3.addWidget(self.lcdNumber_bright, 0, 7, 5, 1)
        self.pushButton_color = QtWidgets.QPushButton(self.groupBox_color_bright)
        self.pushButton_color.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color.sizePolicy().hasHeightForWidth())
        self.pushButton_color.setSizePolicy(sizePolicy)
        self.pushButton_color.setMinimumSize(QtCore.QSize(108, 0))
        self.pushButton_color.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_color.setFlat(False)
        self.pushButton_color.setObjectName("pushButton_color")
        self.gridLayout_3.addWidget(self.pushButton_color, 0, 0, 5, 1)
        self.horizontalSlider_r = QtWidgets.QSlider(self.groupBox_color_bright)
        self.horizontalSlider_r.setEnabled(True)
        self.horizontalSlider_r.setMaximum(255)
        self.horizontalSlider_r.setProperty("value", 0)
        self.horizontalSlider_r.setSliderPosition(0)
        self.horizontalSlider_r.setTracking(True)
        self.horizontalSlider_r.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_r.setInvertedAppearance(False)
        self.horizontalSlider_r.setInvertedControls(False)
        self.horizontalSlider_r.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_r.setTickInterval(0)
        self.horizontalSlider_r.setObjectName("horizontalSlider_r")
        self.gridLayout_3.addWidget(self.horizontalSlider_r, 0, 3, 2, 1)
        self.dial_bright = QtWidgets.QDial(self.groupBox_color_bright)
        self.dial_bright.setEnabled(True)
        self.dial_bright.setMaximum(255)
        self.dial_bright.setProperty("value", 0)
        self.dial_bright.setSliderPosition(0)
        self.dial_bright.setTracking(False)
        self.dial_bright.setOrientation(QtCore.Qt.Horizontal)
        self.dial_bright.setInvertedAppearance(False)
        self.dial_bright.setInvertedControls(False)
        self.dial_bright.setNotchesVisible(False)
        self.dial_bright.setObjectName("dial_bright")
        self.gridLayout_3.addWidget(self.dial_bright, 0, 6, 5, 1)
        self.gridLayout_2.addWidget(self.groupBox_color_bright, 2, 0, 1, 2)
        self.groupBox_last_colors = QtWidgets.QGroupBox(self.tab_light)
        self.groupBox_last_colors.setEnabled(True)
        self.groupBox_last_colors.setObjectName("groupBox_last_colors")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_last_colors)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_last18 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last18.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last18.sizePolicy().hasHeightForWidth())
        self.pushButton_last18.setSizePolicy(sizePolicy)
        self.pushButton_last18.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last18.setFlat(False)
        self.pushButton_last18.setObjectName("pushButton_last18")
        self.gridLayout_5.addWidget(self.pushButton_last18, 4, 3, 1, 1)
        self.pushButton_last11 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last11.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last11.sizePolicy().hasHeightForWidth())
        self.pushButton_last11.setSizePolicy(sizePolicy)
        self.pushButton_last11.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last11.setFlat(False)
        self.pushButton_last11.setObjectName("pushButton_last11")
        self.gridLayout_5.addWidget(self.pushButton_last11, 2, 0, 1, 1)
        self.pushButton_last15 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last15.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last15.sizePolicy().hasHeightForWidth())
        self.pushButton_last15.setSizePolicy(sizePolicy)
        self.pushButton_last15.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last15.setFlat(False)
        self.pushButton_last15.setObjectName("pushButton_last15")
        self.gridLayout_5.addWidget(self.pushButton_last15, 2, 5, 1, 1)
        self.pushButton_last04 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last04.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last04.sizePolicy().hasHeightForWidth())
        self.pushButton_last04.setSizePolicy(sizePolicy)
        self.pushButton_last04.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last04.setFlat(False)
        self.pushButton_last04.setObjectName("pushButton_last04")
        self.gridLayout_5.addWidget(self.pushButton_last04, 0, 4, 1, 1)
        self.pushButton_last17 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last17.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last17.sizePolicy().hasHeightForWidth())
        self.pushButton_last17.setSizePolicy(sizePolicy)
        self.pushButton_last17.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last17.setFlat(False)
        self.pushButton_last17.setObjectName("pushButton_last17")
        self.gridLayout_5.addWidget(self.pushButton_last17, 4, 1, 1, 1)
        self.pushButton_last05 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last05.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last05.sizePolicy().hasHeightForWidth())
        self.pushButton_last05.setSizePolicy(sizePolicy)
        self.pushButton_last05.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last05.setFlat(False)
        self.pushButton_last05.setObjectName("pushButton_last05")
        self.gridLayout_5.addWidget(self.pushButton_last05, 0, 5, 1, 1)
        self.pushButton_last12 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last12.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last12.sizePolicy().hasHeightForWidth())
        self.pushButton_last12.setSizePolicy(sizePolicy)
        self.pushButton_last12.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last12.setFlat(False)
        self.pushButton_last12.setObjectName("pushButton_last12")
        self.gridLayout_5.addWidget(self.pushButton_last12, 2, 1, 1, 1)
        self.pushButton_last08 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last08.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last08.sizePolicy().hasHeightForWidth())
        self.pushButton_last08.setSizePolicy(sizePolicy)
        self.pushButton_last08.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last08.setFlat(False)
        self.pushButton_last08.setObjectName("pushButton_last08")
        self.gridLayout_5.addWidget(self.pushButton_last08, 1, 3, 1, 1)
        self.pushButton_last16 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last16.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last16.sizePolicy().hasHeightForWidth())
        self.pushButton_last16.setSizePolicy(sizePolicy)
        self.pushButton_last16.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last16.setFlat(False)
        self.pushButton_last16.setObjectName("pushButton_last16")
        self.gridLayout_5.addWidget(self.pushButton_last16, 4, 0, 1, 1)
        self.pushButton_last07 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last07.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last07.sizePolicy().hasHeightForWidth())
        self.pushButton_last07.setSizePolicy(sizePolicy)
        self.pushButton_last07.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last07.setFlat(False)
        self.pushButton_last07.setObjectName("pushButton_last07")
        self.gridLayout_5.addWidget(self.pushButton_last07, 1, 1, 1, 1)
        self.pushButton_last14 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last14.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last14.sizePolicy().hasHeightForWidth())
        self.pushButton_last14.setSizePolicy(sizePolicy)
        self.pushButton_last14.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last14.setFlat(False)
        self.pushButton_last14.setObjectName("pushButton_last14")
        self.gridLayout_5.addWidget(self.pushButton_last14, 2, 4, 1, 1)
        self.pushButton_last20 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last20.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last20.sizePolicy().hasHeightForWidth())
        self.pushButton_last20.setSizePolicy(sizePolicy)
        self.pushButton_last20.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last20.setFlat(False)
        self.pushButton_last20.setObjectName("pushButton_last20")
        self.gridLayout_5.addWidget(self.pushButton_last20, 4, 5, 1, 1)
        self.pushButton_last09 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last09.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last09.sizePolicy().hasHeightForWidth())
        self.pushButton_last09.setSizePolicy(sizePolicy)
        self.pushButton_last09.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last09.setFlat(False)
        self.pushButton_last09.setObjectName("pushButton_last09")
        self.gridLayout_5.addWidget(self.pushButton_last09, 1, 4, 1, 1)
        self.pushButton_last13 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last13.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last13.sizePolicy().hasHeightForWidth())
        self.pushButton_last13.setSizePolicy(sizePolicy)
        self.pushButton_last13.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last13.setFlat(False)
        self.pushButton_last13.setObjectName("pushButton_last13")
        self.gridLayout_5.addWidget(self.pushButton_last13, 2, 3, 1, 1)
        self.pushButton_last10 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last10.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last10.sizePolicy().hasHeightForWidth())
        self.pushButton_last10.setSizePolicy(sizePolicy)
        self.pushButton_last10.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last10.setFlat(False)
        self.pushButton_last10.setObjectName("pushButton_last10")
        self.gridLayout_5.addWidget(self.pushButton_last10, 1, 5, 1, 1)
        self.pushButton_last02 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last02.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last02.sizePolicy().hasHeightForWidth())
        self.pushButton_last02.setSizePolicy(sizePolicy)
        self.pushButton_last02.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last02.setFlat(False)
        self.pushButton_last02.setObjectName("pushButton_last02")
        self.gridLayout_5.addWidget(self.pushButton_last02, 0, 1, 1, 1)
        self.pushButton_last19 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last19.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last19.sizePolicy().hasHeightForWidth())
        self.pushButton_last19.setSizePolicy(sizePolicy)
        self.pushButton_last19.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last19.setFlat(False)
        self.pushButton_last19.setObjectName("pushButton_last19")
        self.gridLayout_5.addWidget(self.pushButton_last19, 4, 4, 1, 1)
        self.pushButton_last03 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last03.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last03.sizePolicy().hasHeightForWidth())
        self.pushButton_last03.setSizePolicy(sizePolicy)
        self.pushButton_last03.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last03.setFlat(False)
        self.pushButton_last03.setObjectName("pushButton_last03")
        self.gridLayout_5.addWidget(self.pushButton_last03, 0, 3, 1, 1)
        self.pushButton_last01 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last01.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last01.sizePolicy().hasHeightForWidth())
        self.pushButton_last01.setSizePolicy(sizePolicy)
        self.pushButton_last01.setAutoFillBackground(False)
        self.pushButton_last01.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last01.setAutoDefault(False)
        self.pushButton_last01.setDefault(False)
        self.pushButton_last01.setFlat(False)
        self.pushButton_last01.setObjectName("pushButton_last01")
        self.gridLayout_5.addWidget(self.pushButton_last01, 0, 0, 1, 1)
        self.pushButton_last06 = QtWidgets.QPushButton(self.groupBox_last_colors)
        self.pushButton_last06.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last06.sizePolicy().hasHeightForWidth())
        self.pushButton_last06.setSizePolicy(sizePolicy)
        self.pushButton_last06.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_last06.setFlat(False)
        self.pushButton_last06.setObjectName("pushButton_last06")
        self.gridLayout_5.addWidget(self.pushButton_last06, 1, 0, 1, 1)
        self.pushButton_last01.raise_()
        self.pushButton_last07.raise_()
        self.pushButton_last06.raise_()
        self.pushButton_last08.raise_()
        self.pushButton_last16.raise_()
        self.pushButton_last18.raise_()
        self.pushButton_last17.raise_()
        self.pushButton_last02.raise_()
        self.pushButton_last03.raise_()
        self.pushButton_last11.raise_()
        self.pushButton_last12.raise_()
        self.pushButton_last19.raise_()
        self.pushButton_last09.raise_()
        self.pushButton_last14.raise_()
        self.pushButton_last04.raise_()
        self.pushButton_last05.raise_()
        self.pushButton_last10.raise_()
        self.pushButton_last15.raise_()
        self.pushButton_last20.raise_()
        self.pushButton_last13.raise_()
        self.gridLayout_2.addWidget(self.groupBox_last_colors, 0, 0, 1, 2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/128x128/actions/application-exit-5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_light, icon, "")
        self.tab_ilumination = QtWidgets.QWidget()
        self.tab_ilumination.setObjectName("tab_ilumination")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_ilumination)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_effect2 = QtWidgets.QGroupBox(self.tab_ilumination)
        self.groupBox_effect2.setEnabled(True)
        self.groupBox_effect2.setObjectName("groupBox_effect2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_effect2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.plainTextEdit_input2 = QtWidgets.QPlainTextEdit(self.groupBox_effect2)
        self.plainTextEdit_input2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.plainTextEdit_input2.setFont(font)
        self.plainTextEdit_input2.setObjectName("plainTextEdit_input2")
        self.gridLayout_8.addWidget(self.plainTextEdit_input2, 0, 2, 5, 1)
        self.spinBox_time2 = QtWidgets.QSpinBox(self.groupBox_effect2)
        self.spinBox_time2.setEnabled(True)
        self.spinBox_time2.setMaximum(10000)
        self.spinBox_time2.setProperty("value", 500)
        self.spinBox_time2.setObjectName("spinBox_time2")
        self.gridLayout_8.addWidget(self.spinBox_time2, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_effect2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 3, 1, 1, 1)
        self.comboBox_effect2 = QtWidgets.QComboBox(self.groupBox_effect2)
        self.comboBox_effect2.setEnabled(True)
        self.comboBox_effect2.setObjectName("comboBox_effect2")
        self.gridLayout_8.addWidget(self.comboBox_effect2, 1, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox_effect2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 0, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.groupBox_effect2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 2, 0, 1, 2)
        self.pushButton_effect2 = QtWidgets.QPushButton(self.groupBox_effect2)
        self.pushButton_effect2.setEnabled(True)
        self.pushButton_effect2.setCheckable(True)
        self.pushButton_effect2.setObjectName("pushButton_effect2")
        self.gridLayout_8.addWidget(self.pushButton_effect2, 4, 0, 1, 2)
        self.gridLayout_6.addWidget(self.groupBox_effect2, 0, 1, 1, 1)
        self.groupBox_effect3 = QtWidgets.QGroupBox(self.tab_ilumination)
        self.groupBox_effect3.setEnabled(True)
        self.groupBox_effect3.setObjectName("groupBox_effect3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_effect3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.spinBox_time3 = QtWidgets.QSpinBox(self.groupBox_effect3)
        self.spinBox_time3.setEnabled(True)
        self.spinBox_time3.setMaximum(10000)
        self.spinBox_time3.setProperty("value", 500)
        self.spinBox_time3.setObjectName("spinBox_time3")
        self.gridLayout_9.addWidget(self.spinBox_time3, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_effect3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_effect3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 0, 0, 1, 2)
        self.comboBox_effect3 = QtWidgets.QComboBox(self.groupBox_effect3)
        self.comboBox_effect3.setEnabled(True)
        self.comboBox_effect3.setObjectName("comboBox_effect3")
        self.gridLayout_9.addWidget(self.comboBox_effect3, 1, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.groupBox_effect3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 2, 0, 1, 2)
        self.pushButton_effect3 = QtWidgets.QPushButton(self.groupBox_effect3)
        self.pushButton_effect3.setEnabled(True)
        self.pushButton_effect3.setCheckable(True)
        self.pushButton_effect3.setObjectName("pushButton_effect3")
        self.gridLayout_9.addWidget(self.pushButton_effect3, 4, 0, 1, 2)
        self.plainTextEdit_input3 = QtWidgets.QPlainTextEdit(self.groupBox_effect3)
        self.plainTextEdit_input3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.plainTextEdit_input3.setFont(font)
        self.plainTextEdit_input3.setObjectName("plainTextEdit_input3")
        self.gridLayout_9.addWidget(self.plainTextEdit_input3, 0, 4, 5, 1)
        self.gridLayout_6.addWidget(self.groupBox_effect3, 2, 0, 1, 1)
        self.groupBox_effect4 = QtWidgets.QGroupBox(self.tab_ilumination)
        self.groupBox_effect4.setEnabled(True)
        self.groupBox_effect4.setObjectName("groupBox_effect4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_effect4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.plainTextEdit_input4 = QtWidgets.QPlainTextEdit(self.groupBox_effect4)
        self.plainTextEdit_input4.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.plainTextEdit_input4.setFont(font)
        self.plainTextEdit_input4.setObjectName("plainTextEdit_input4")
        self.gridLayout_10.addWidget(self.plainTextEdit_input4, 0, 2, 5, 1)
        self.spinBox_time4 = QtWidgets.QSpinBox(self.groupBox_effect4)
        self.spinBox_time4.setEnabled(True)
        self.spinBox_time4.setMaximum(10000)
        self.spinBox_time4.setProperty("value", 500)
        self.spinBox_time4.setObjectName("spinBox_time4")
        self.gridLayout_10.addWidget(self.spinBox_time4, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_effect4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_effect4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 2, 0, 1, 2)
        self.comboBox_effect4 = QtWidgets.QComboBox(self.groupBox_effect4)
        self.comboBox_effect4.setEnabled(True)
        self.comboBox_effect4.setObjectName("comboBox_effect4")
        self.gridLayout_10.addWidget(self.comboBox_effect4, 1, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.groupBox_effect4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 0, 0, 1, 2)
        self.pushButton_effect4 = QtWidgets.QPushButton(self.groupBox_effect4)
        self.pushButton_effect4.setEnabled(True)
        self.pushButton_effect4.setCheckable(True)
        self.pushButton_effect4.setObjectName("pushButton_effect4")
        self.gridLayout_10.addWidget(self.pushButton_effect4, 4, 0, 1, 2)
        self.gridLayout_6.addWidget(self.groupBox_effect4, 2, 1, 1, 1)
        self.groupBox_effect1 = QtWidgets.QGroupBox(self.tab_ilumination)
        self.groupBox_effect1.setEnabled(True)
        self.groupBox_effect1.setObjectName("groupBox_effect1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_effect1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.spinBox_time1 = QtWidgets.QSpinBox(self.groupBox_effect1)
        self.spinBox_time1.setEnabled(True)
        self.spinBox_time1.setMaximum(10000)
        self.spinBox_time1.setProperty("value", 500)
        self.spinBox_time1.setObjectName("spinBox_time1")
        self.gridLayout_7.addWidget(self.spinBox_time1, 3, 2, 1, 1)
        self.pushButton_effect1 = QtWidgets.QPushButton(self.groupBox_effect1)
        self.pushButton_effect1.setEnabled(True)
        self.pushButton_effect1.setCheckable(True)
        self.pushButton_effect1.setObjectName("pushButton_effect1")
        self.gridLayout_7.addWidget(self.pushButton_effect1, 4, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_effect1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_effect1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 2, 2, 1, 2)
        self.comboBox_effect1 = QtWidgets.QComboBox(self.groupBox_effect1)
        self.comboBox_effect1.setEnabled(True)
        self.comboBox_effect1.setObjectName("comboBox_effect1")
        self.gridLayout_7.addWidget(self.comboBox_effect1, 1, 2, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_effect1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 2, 1, 2)
        self.plainTextEdit_input1 = QtWidgets.QPlainTextEdit(self.groupBox_effect1)
        self.plainTextEdit_input1.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.plainTextEdit_input1.setFont(font)
        self.plainTextEdit_input1.setObjectName("plainTextEdit_input1")
        self.gridLayout_7.addWidget(self.plainTextEdit_input1, 0, 4, 5, 1)
        self.gridLayout_6.addWidget(self.groupBox_effect1, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/128x128/actions/application-exit-4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_ilumination, icon1, "")
        self.tab_sound = QtWidgets.QWidget()
        self.tab_sound.setObjectName("tab_sound")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_sound)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_23 = QtWidgets.QLabel(self.tab_sound)
        self.label_23.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_15.addWidget(self.label_23, 0, 0, 1, 1)
        self.comboBox_effect_music = QtWidgets.QComboBox(self.tab_sound)
        self.comboBox_effect_music.setEnabled(True)
        self.comboBox_effect_music.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_effect_music.setObjectName("comboBox_effect_music")
        self.gridLayout_15.addWidget(self.comboBox_effect_music, 0, 6, 1, 1)
        self.pushButton_sound_onoff = QtWidgets.QPushButton(self.tab_sound)
        self.pushButton_sound_onoff.setCheckable(True)
        self.pushButton_sound_onoff.setObjectName("pushButton_sound_onoff")
        self.gridLayout_15.addWidget(self.pushButton_sound_onoff, 3, 0, 1, 7)
        self.label_41 = QtWidgets.QLabel(self.tab_sound)
        self.label_41.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_15.addWidget(self.label_41, 0, 5, 1, 1)
        self.comboBox_input = QtWidgets.QComboBox(self.tab_sound)
        self.comboBox_input.setEnabled(True)
        self.comboBox_input.setObjectName("comboBox_input")
        self.gridLayout_15.addWidget(self.comboBox_input, 0, 1, 1, 4)
        self.groupBox_bit_detect = QtWidgets.QGroupBox(self.tab_sound)
        self.groupBox_bit_detect.setObjectName("groupBox_bit_detect")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_bit_detect)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit_bitdetector = QtWidgets.QPlainTextEdit(self.groupBox_bit_detect)
        self.plainTextEdit_bitdetector.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_bitdetector.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_bitdetector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.plainTextEdit_bitdetector.setFont(font)
        self.plainTextEdit_bitdetector.setDocumentTitle("")
        self.plainTextEdit_bitdetector.setBackgroundVisible(False)
        self.plainTextEdit_bitdetector.setObjectName("plainTextEdit_bitdetector")
        self.horizontalLayout.addWidget(self.plainTextEdit_bitdetector)
        self.gridLayout_15.addWidget(self.groupBox_bit_detect, 1, 5, 1, 2)
        self.groupBox_freq = QtWidgets.QGroupBox(self.tab_sound)
        self.groupBox_freq.setEnabled(True)
        self.groupBox_freq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_freq.setObjectName("groupBox_freq")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_freq)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.spinBox_noise = QtWidgets.QSpinBox(self.groupBox_freq)
        self.spinBox_noise.setMaximum(10000)
        self.spinBox_noise.setSingleStep(100)
        self.spinBox_noise.setProperty("value", 1000)
        self.spinBox_noise.setObjectName("spinBox_noise")
        self.gridLayout_16.addWidget(self.spinBox_noise, 5, 6, 1, 1)
        self.horizontalSlider_noise = QtWidgets.QSlider(self.groupBox_freq)
        self.horizontalSlider_noise.setMaximum(10000)
        self.horizontalSlider_noise.setSingleStep(100)
        self.horizontalSlider_noise.setPageStep(1000)
        self.horizontalSlider_noise.setProperty("value", 1000)
        self.horizontalSlider_noise.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_noise.setObjectName("horizontalSlider_noise")
        self.gridLayout_16.addWidget(self.horizontalSlider_noise, 5, 1, 1, 5)
        self.doubleSpinBox_mult_high = QtWidgets.QDoubleSpinBox(self.groupBox_freq)
        self.doubleSpinBox_mult_high.setMaximum(1.0)
        self.doubleSpinBox_mult_high.setSingleStep(0.1)
        self.doubleSpinBox_mult_high.setProperty("value", 1.0)
        self.doubleSpinBox_mult_high.setObjectName("doubleSpinBox_mult_high")
        self.gridLayout_16.addWidget(self.doubleSpinBox_mult_high, 2, 5, 1, 2)
        self.doubleSpinBox_mult_low = QtWidgets.QDoubleSpinBox(self.groupBox_freq)
        self.doubleSpinBox_mult_low.setMaximum(1.0)
        self.doubleSpinBox_mult_low.setSingleStep(0.1)
        self.doubleSpinBox_mult_low.setProperty("value", 1.0)
        self.doubleSpinBox_mult_low.setObjectName("doubleSpinBox_mult_low")
        self.gridLayout_16.addWidget(self.doubleSpinBox_mult_low, 2, 1, 1, 2)
        self.doubleSpinBox_mult_mid = QtWidgets.QDoubleSpinBox(self.groupBox_freq)
        self.doubleSpinBox_mult_mid.setMaximum(1.0)
        self.doubleSpinBox_mult_mid.setSingleStep(0.1)
        self.doubleSpinBox_mult_mid.setProperty("value", 1.0)
        self.doubleSpinBox_mult_mid.setObjectName("doubleSpinBox_mult_mid")
        self.gridLayout_16.addWidget(self.doubleSpinBox_mult_mid, 2, 3, 1, 2)
        self.pushButton_color_high = QtWidgets.QPushButton(self.groupBox_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color_high.sizePolicy().hasHeightForWidth())
        self.pushButton_color_high.setSizePolicy(sizePolicy)
        self.pushButton_color_high.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_color_high.setMaximumSize(QtCore.QSize(16777215, 200))
        self.pushButton_color_high.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_color_high.setObjectName("pushButton_color_high")
        self.gridLayout_16.addWidget(self.pushButton_color_high, 1, 5, 1, 2)
        self.pushButton_color_low = QtWidgets.QPushButton(self.groupBox_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color_low.sizePolicy().hasHeightForWidth())
        self.pushButton_color_low.setSizePolicy(sizePolicy)
        self.pushButton_color_low.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_color_low.setMaximumSize(QtCore.QSize(16777215, 200))
        self.pushButton_color_low.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_color_low.setObjectName("pushButton_color_low")
        self.gridLayout_16.addWidget(self.pushButton_color_low, 1, 1, 1, 2)
        self.pushButton_color_mid = QtWidgets.QPushButton(self.groupBox_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color_mid.sizePolicy().hasHeightForWidth())
        self.pushButton_color_mid.setSizePolicy(sizePolicy)
        self.pushButton_color_mid.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_color_mid.setMaximumSize(QtCore.QSize(16777215, 200))
        self.pushButton_color_mid.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_color_mid.setObjectName("pushButton_color_mid")
        self.gridLayout_16.addWidget(self.pushButton_color_mid, 1, 3, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.groupBox_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_16.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_16.addWidget(self.label_24, 0, 3, 1, 1)
        self.verticalSlider_lower_low = QtWidgets.QSlider(self.groupBox_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_lower_low.sizePolicy().hasHeightForWidth())
        self.verticalSlider_lower_low.setSizePolicy(sizePolicy)
        self.verticalSlider_lower_low.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalSlider_lower_low.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalSlider_lower_low.setMinimum(20)
        self.verticalSlider_lower_low.setMaximum(200)
        self.verticalSlider_lower_low.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_lower_low.setObjectName("verticalSlider_lower_low")
        self.gridLayout_16.addWidget(self.verticalSlider_lower_low, 3, 1, 1, 1)
        self.spinBox_lower_high = QtWidgets.QSpinBox(self.groupBox_freq)
        self.spinBox_lower_high.setSuffix("")
        self.spinBox_lower_high.setMinimum(1000)
        self.spinBox_lower_high.setMaximum(20000)
        self.spinBox_lower_high.setProperty("value", 1000)
        self.spinBox_lower_high.setObjectName("spinBox_lower_high")
        self.gridLayout_16.addWidget(self.spinBox_lower_high, 4, 5, 1, 1)
        self.spinBox_higher_high = QtWidgets.QSpinBox(self.groupBox_freq)
        self.spinBox_higher_high.setSuffix("")
        self.spinBox_higher_high.setMinimum(1000)
        self.spinBox_higher_high.setMaximum(20000)
        self.spinBox_higher_high.setProperty("value", 1000)
        self.spinBox_higher_high.setObjectName("spinBox_higher_high")
        self.gridLayout_16.addWidget(self.spinBox_higher_high, 4, 6, 1, 1)
        self.spinBox_higher_low = QtWidgets.QSpinBox(self.groupBox_freq)
        self.spinBox_higher_low.setSuffix("")
        self.spinBox_higher_low.setMinimum(20)
        self.spinBox_higher_low.setMaximum(200)
        self.spinBox_higher_low.setProperty("value", 100)
        self.spinBox_higher_low.setObjectName("spinBox_higher_low")
        self.gridLayout_16.addWidget(self.spinBox_higher_low, 4, 2, 1, 1)
        self.spinBox_higher_mid = QtWidgets.QSpinBox(self.groupBox_freq)
        self.spinBox_higher_mid.setMinimum(100)
        self.spinBox_higher_mid.setMaximum(2000)
        self.spinBox_higher_mid.setProperty("value", 1000)
        self.spinBox_higher_mid.setObjectName("spinBox_higher_mid")
        self.gridLayout_16.addWidget(self.spinBox_higher_mid, 4, 4, 1, 1)
        self.spinBox_lower_mid = QtWidgets.QSpinBox(self.groupBox_freq)
        self.spinBox_lower_mid.setMinimum(100)
        self.spinBox_lower_mid.setMaximum(2000)
        self.spinBox_lower_mid.setObjectName("spinBox_lower_mid")
        self.gridLayout_16.addWidget(self.spinBox_lower_mid, 4, 3, 1, 1)
        self.verticalSlider_higher_high = QtWidgets.QSlider(self.groupBox_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_higher_high.sizePolicy().hasHeightForWidth())
        self.verticalSlider_higher_high.setSizePolicy(sizePolicy)
        self.verticalSlider_higher_high.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalSlider_higher_high.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalSlider_higher_high.setMinimum(1000)
        self.verticalSlider_higher_high.setMaximum(20000)
        self.verticalSlider_higher_high.setProperty("value", 20000)
        self.verticalSlider_higher_high.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_higher_high.setObjectName("verticalSlider_higher_high")
        self.gridLayout_16.addWidget(self.verticalSlider_higher_high, 3, 6, 1, 1)
        self.spinBox_lower_low = QtWidgets.QSpinBox(self.groupBox_freq)
        self.spinBox_lower_low.setSuffix("")
        self.spinBox_lower_low.setPrefix("")
        self.spinBox_lower_low.setMinimum(20)
        self.spinBox_lower_low.setMaximum(200)
        self.spinBox_lower_low.setObjectName("spinBox_lower_low")
        self.gridLayout_16.addWidget(self.spinBox_lower_low, 4, 1, 1, 1)
        self.verticalSlider_lower_high = QtWidgets.QSlider(self.groupBox_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_lower_high.sizePolicy().hasHeightForWidth())
        self.verticalSlider_lower_high.setSizePolicy(sizePolicy)
        self.verticalSlider_lower_high.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalSlider_lower_high.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalSlider_lower_high.setMinimum(1000)
        self.verticalSlider_lower_high.setMaximum(20000)
        self.verticalSlider_lower_high.setProperty("value", 1000)
        self.verticalSlider_lower_high.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_lower_high.setObjectName("verticalSlider_lower_high")
        self.gridLayout_16.addWidget(self.verticalSlider_lower_high, 3, 5, 1, 1)
        self.verticalSlider_lower_mid = QtWidgets.QSlider(self.groupBox_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_lower_mid.sizePolicy().hasHeightForWidth())
        self.verticalSlider_lower_mid.setSizePolicy(sizePolicy)
        self.verticalSlider_lower_mid.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalSlider_lower_mid.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalSlider_lower_mid.setMinimum(100)
        self.verticalSlider_lower_mid.setMaximum(2000)
        self.verticalSlider_lower_mid.setProperty("value", 100)
        self.verticalSlider_lower_mid.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_lower_mid.setObjectName("verticalSlider_lower_mid")
        self.gridLayout_16.addWidget(self.verticalSlider_lower_mid, 3, 3, 1, 1)
        self.verticalSlider_higher_mid = QtWidgets.QSlider(self.groupBox_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_higher_mid.sizePolicy().hasHeightForWidth())
        self.verticalSlider_higher_mid.setSizePolicy(sizePolicy)
        self.verticalSlider_higher_mid.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalSlider_higher_mid.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalSlider_higher_mid.setMinimum(100)
        self.verticalSlider_higher_mid.setMaximum(2000)
        self.verticalSlider_higher_mid.setProperty("value", 1000)
        self.verticalSlider_higher_mid.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_higher_mid.setObjectName("verticalSlider_higher_mid")
        self.gridLayout_16.addWidget(self.verticalSlider_higher_mid, 3, 4, 1, 1)
        self.verticalSlider_higher_low = QtWidgets.QSlider(self.groupBox_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_higher_low.sizePolicy().hasHeightForWidth())
        self.verticalSlider_higher_low.setSizePolicy(sizePolicy)
        self.verticalSlider_higher_low.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalSlider_higher_low.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalSlider_higher_low.setMinimum(20)
        self.verticalSlider_higher_low.setMaximum(200)
        self.verticalSlider_higher_low.setProperty("value", 100)
        self.verticalSlider_higher_low.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_higher_low.setObjectName("verticalSlider_higher_low")
        self.gridLayout_16.addWidget(self.verticalSlider_higher_low, 3, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_16.addWidget(self.label_25, 0, 5, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_freq)
        self.label_26.setObjectName("label_26")
        self.gridLayout_16.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_freq)
        self.label_42.setObjectName("label_42")
        self.gridLayout_16.addWidget(self.label_42, 2, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_freq)
        self.label_45.setObjectName("label_45")
        self.gridLayout_16.addWidget(self.label_45, 5, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_freq)
        self.label_43.setObjectName("label_43")
        self.gridLayout_16.addWidget(self.label_43, 3, 0, 2, 1)
        self.gridLayout_15.addWidget(self.groupBox_freq, 1, 0, 2, 5)
        self.tabWidget.addTab(self.tab_sound, "")
        self.tab_ext_backlight = QtWidgets.QWidget()
        self.tab_ext_backlight.setObjectName("tab_ext_backlight")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_ext_backlight)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_setup_ext = QtWidgets.QGroupBox(self.tab_ext_backlight)
        self.groupBox_setup_ext.setEnabled(True)
        self.groupBox_setup_ext.setObjectName("groupBox_setup_ext")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_setup_ext)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.pushButton_zones = QtWidgets.QPushButton(self.groupBox_setup_ext)
        self.pushButton_zones.setCheckable(True)
        self.pushButton_zones.setObjectName("pushButton_zones")
        self.gridLayout_19.addWidget(self.pushButton_zones, 0, 1, 1, 2)
        self.label_38 = QtWidgets.QLabel(self.groupBox_setup_ext)
        self.label_38.setObjectName("label_38")
        self.gridLayout_19.addWidget(self.label_38, 6, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_setup_ext)
        self.label_36.setObjectName("label_36")
        self.gridLayout_19.addWidget(self.label_36, 8, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_setup_ext)
        self.label_39.setObjectName("label_39")
        self.gridLayout_19.addWidget(self.label_39, 7, 1, 1, 1)
        self.comboBox_effect_backlight = QtWidgets.QComboBox(self.groupBox_setup_ext)
        self.comboBox_effect_backlight.setObjectName("comboBox_effect_backlight")
        self.gridLayout_19.addWidget(self.comboBox_effect_backlight, 6, 2, 1, 1)
        self.spinBox_effect = QtWidgets.QSpinBox(self.groupBox_setup_ext)
        self.spinBox_effect.setMaximum(5000)
        self.spinBox_effect.setSingleStep(50)
        self.spinBox_effect.setProperty("value", 100)
        self.spinBox_effect.setObjectName("spinBox_effect")
        self.gridLayout_19.addWidget(self.spinBox_effect, 7, 2, 1, 1)
        self.spinBox_update = QtWidgets.QSpinBox(self.groupBox_setup_ext)
        self.spinBox_update.setMinimum(100)
        self.spinBox_update.setMaximum(5000)
        self.spinBox_update.setSingleStep(50)
        self.spinBox_update.setProperty("value", 250)
        self.spinBox_update.setObjectName("spinBox_update")
        self.gridLayout_19.addWidget(self.spinBox_update, 8, 2, 1, 1)
        self.spinBox_count_zones = QtWidgets.QSpinBox(self.groupBox_setup_ext)
        self.spinBox_count_zones.setMaximum(6)
        self.spinBox_count_zones.setProperty("value", 6)
        self.spinBox_count_zones.setObjectName("spinBox_count_zones")
        self.gridLayout_19.addWidget(self.spinBox_count_zones, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_setup_ext)
        self.label_4.setObjectName("label_4")
        self.gridLayout_19.addWidget(self.label_4, 1, 1, 1, 1)
        self.pushButton_ext_on_off = QtWidgets.QPushButton(self.groupBox_setup_ext)
        self.pushButton_ext_on_off.setCheckable(True)
        self.pushButton_ext_on_off.setObjectName("pushButton_ext_on_off")
        self.gridLayout_19.addWidget(self.pushButton_ext_on_off, 10, 1, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox_setup_ext, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_ext_backlight, "")
        self.tab_setup = QtWidgets.QWidget()
        self.tab_setup.setObjectName("tab_setup")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_setup)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_wb = QtWidgets.QGroupBox(self.tab_setup)
        self.groupBox_wb.setEnabled(True)
        self.groupBox_wb.setObjectName("groupBox_wb")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_wb)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalSlider_wb_r = QtWidgets.QSlider(self.groupBox_wb)
        self.horizontalSlider_wb_r.setMaximum(511)
        self.horizontalSlider_wb_r.setProperty("value", 511)
        self.horizontalSlider_wb_r.setSliderPosition(511)
        self.horizontalSlider_wb_r.setTracking(True)
        self.horizontalSlider_wb_r.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_wb_r.setInvertedAppearance(False)
        self.horizontalSlider_wb_r.setInvertedControls(False)
        self.horizontalSlider_wb_r.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_wb_r.setTickInterval(0)
        self.horizontalSlider_wb_r.setObjectName("horizontalSlider_wb_r")
        self.gridLayout_12.addWidget(self.horizontalSlider_wb_r, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_wb)
        self.label_20.setObjectName("label_20")
        self.gridLayout_12.addWidget(self.label_20, 0, 0, 1, 1)
        self.spinBox_wb_r = QtWidgets.QSpinBox(self.groupBox_wb)
        self.spinBox_wb_r.setWrapping(False)
        self.spinBox_wb_r.setFrame(True)
        self.spinBox_wb_r.setReadOnly(False)
        self.spinBox_wb_r.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_wb_r.setAccelerated(False)
        self.spinBox_wb_r.setProperty("showGroupSeparator", False)
        self.spinBox_wb_r.setMaximum(511)
        self.spinBox_wb_r.setProperty("value", 511)
        self.spinBox_wb_r.setObjectName("spinBox_wb_r")
        self.gridLayout_12.addWidget(self.spinBox_wb_r, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_wb)
        self.label_19.setObjectName("label_19")
        self.gridLayout_12.addWidget(self.label_19, 1, 0, 1, 1)
        self.horizontalSlider_wb_g = QtWidgets.QSlider(self.groupBox_wb)
        self.horizontalSlider_wb_g.setMaximum(511)
        self.horizontalSlider_wb_g.setProperty("value", 511)
        self.horizontalSlider_wb_g.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_wb_g.setObjectName("horizontalSlider_wb_g")
        self.gridLayout_12.addWidget(self.horizontalSlider_wb_g, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_wb)
        self.label_21.setObjectName("label_21")
        self.gridLayout_12.addWidget(self.label_21, 2, 0, 1, 1)
        self.horizontalSlider_wb_b = QtWidgets.QSlider(self.groupBox_wb)
        self.horizontalSlider_wb_b.setMaximum(511)
        self.horizontalSlider_wb_b.setProperty("value", 511)
        self.horizontalSlider_wb_b.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_wb_b.setObjectName("horizontalSlider_wb_b")
        self.gridLayout_12.addWidget(self.horizontalSlider_wb_b, 2, 1, 1, 1)
        self.spinBox_wb_b = QtWidgets.QSpinBox(self.groupBox_wb)
        self.spinBox_wb_b.setWrapping(False)
        self.spinBox_wb_b.setFrame(True)
        self.spinBox_wb_b.setReadOnly(False)
        self.spinBox_wb_b.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_wb_b.setAccelerated(False)
        self.spinBox_wb_b.setProperty("showGroupSeparator", False)
        self.spinBox_wb_b.setMaximum(511)
        self.spinBox_wb_b.setProperty("value", 511)
        self.spinBox_wb_b.setObjectName("spinBox_wb_b")
        self.gridLayout_12.addWidget(self.spinBox_wb_b, 2, 2, 1, 1)
        self.spinBox_wb_g = QtWidgets.QSpinBox(self.groupBox_wb)
        self.spinBox_wb_g.setWrapping(False)
        self.spinBox_wb_g.setFrame(True)
        self.spinBox_wb_g.setReadOnly(False)
        self.spinBox_wb_g.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_wb_g.setAccelerated(False)
        self.spinBox_wb_g.setProperty("showGroupSeparator", False)
        self.spinBox_wb_g.setMaximum(511)
        self.spinBox_wb_g.setProperty("value", 511)
        self.spinBox_wb_g.setObjectName("spinBox_wb_g")
        self.gridLayout_12.addWidget(self.spinBox_wb_g, 1, 2, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_wb, 1, 0, 1, 1)
        self.groupBox_gamma = QtWidgets.QGroupBox(self.tab_setup)
        self.groupBox_gamma.setEnabled(True)
        self.groupBox_gamma.setObjectName("groupBox_gamma")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_gamma)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.graphicsView_gamma = PlotWidget(self.groupBox_gamma)
        self.graphicsView_gamma.setObjectName("graphicsView_gamma")
        self.gridLayout_13.addWidget(self.graphicsView_gamma, 0, 0, 1, 1)
        self.doubleSpinBox_gamma = QtWidgets.QDoubleSpinBox(self.groupBox_gamma)
        self.doubleSpinBox_gamma.setMinimum(1.0)
        self.doubleSpinBox_gamma.setMaximum(10.0)
        self.doubleSpinBox_gamma.setSingleStep(0.1)
        self.doubleSpinBox_gamma.setProperty("value", 2.8)
        self.doubleSpinBox_gamma.setObjectName("doubleSpinBox_gamma")
        self.gridLayout_13.addWidget(self.doubleSpinBox_gamma, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_gamma, 1, 2, 1, 1)
        self.groupBox_device = QtWidgets.QGroupBox(self.tab_setup)
        self.groupBox_device.setObjectName("groupBox_device")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_device)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.comboBox_device = QtWidgets.QComboBox(self.groupBox_device)
        self.comboBox_device.setEnabled(True)
        self.comboBox_device.setObjectName("comboBox_device")
        self.gridLayout_14.addWidget(self.comboBox_device, 0, 0, 1, 1)
        self.label_device = QtWidgets.QLabel(self.groupBox_device)
        self.label_device.setText("")
        self.label_device.setObjectName("label_device")
        self.gridLayout_14.addWidget(self.label_device, 0, 2, 1, 1)
        self.pushButton_update = QtWidgets.QPushButton(self.groupBox_device)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_update.sizePolicy().hasHeightForWidth())
        self.pushButton_update.setSizePolicy(sizePolicy)
        self.pushButton_update.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/update.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_update.setIcon(icon2)
        self.pushButton_update.setObjectName("pushButton_update")
        self.gridLayout_14.addWidget(self.pushButton_update, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_device, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tab_setup, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_23.setBuddy(self.comboBox_input)
        self.label_41.setBuddy(self.comboBox_effect_music)
        self.label_38.setBuddy(self.comboBox_effect_backlight)
        self.label_36.setBuddy(self.spinBox_update)
        self.label_39.setBuddy(self.spinBox_effect)
        self.label_4.setBuddy(self.spinBox_count_zones)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.horizontalSlider_r.valueChanged['int'].connect(self.spinBox_r.setValue)
        self.horizontalSlider_g.valueChanged['int'].connect(self.spinBox_g.setValue)
        self.horizontalSlider_b.valueChanged['int'].connect(self.spinBox_b.setValue)
        self.horizontalSlider_wb_r.valueChanged['int'].connect(self.spinBox_wb_r.setValue)
        self.horizontalSlider_wb_g.valueChanged['int'].connect(self.spinBox_wb_g.setValue)
        self.spinBox_wb_b.valueChanged['int'].connect(self.horizontalSlider_wb_b.setValue)
        self.horizontalSlider_wb_b.valueChanged['int'].connect(self.spinBox_wb_b.setValue)
        self.spinBox_wb_g.valueChanged['int'].connect(self.horizontalSlider_wb_g.setValue)
        self.spinBox_wb_r.valueChanged['int'].connect(self.horizontalSlider_wb_r.setValue)
        self.spinBox_r.valueChanged['int'].connect(self.horizontalSlider_r.setValue)
        self.spinBox_g.valueChanged['int'].connect(self.horizontalSlider_g.setValue)
        self.spinBox_b.valueChanged['int'].connect(self.horizontalSlider_b.setValue)
        self.dial_bright.sliderMoved['int'].connect(self.lcdNumber_bright.display)
        self.dial_bright.valueChanged['int'].connect(self.lcdNumber_bright.display)
        self.verticalSlider_lower_low.valueChanged['int'].connect(self.spinBox_lower_low.setValue)
        self.verticalSlider_higher_low.valueChanged['int'].connect(self.spinBox_higher_low.setValue)
        self.verticalSlider_lower_high.valueChanged['int'].connect(self.spinBox_lower_high.setValue)
        self.verticalSlider_higher_high.valueChanged['int'].connect(self.spinBox_higher_high.setValue)
        self.spinBox_lower_low.valueChanged['int'].connect(self.verticalSlider_lower_low.setValue)
        self.spinBox_higher_low.valueChanged['int'].connect(self.verticalSlider_higher_low.setValue)
        self.spinBox_lower_high.valueChanged['int'].connect(self.verticalSlider_lower_high.setValue)
        self.spinBox_higher_high.valueChanged['int'].connect(self.verticalSlider_higher_high.setValue)
        self.horizontalSlider_noise.valueChanged['int'].connect(self.spinBox_noise.setValue)
        self.spinBox_noise.valueChanged['int'].connect(self.horizontalSlider_noise.setValue)
        self.verticalSlider_lower_mid.valueChanged['int'].connect(self.spinBox_lower_mid.setValue)
        self.spinBox_lower_mid.valueChanged['int'].connect(self.verticalSlider_lower_mid.setValue)
        self.verticalSlider_higher_mid.valueChanged['int'].connect(self.spinBox_higher_mid.setValue)
        self.spinBox_higher_mid.valueChanged['int'].connect(self.verticalSlider_higher_mid.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_color, self.horizontalSlider_r)
        MainWindow.setTabOrder(self.horizontalSlider_r, self.spinBox_r)
        MainWindow.setTabOrder(self.spinBox_r, self.horizontalSlider_g)
        MainWindow.setTabOrder(self.horizontalSlider_g, self.spinBox_g)
        MainWindow.setTabOrder(self.spinBox_g, self.horizontalSlider_b)
        MainWindow.setTabOrder(self.horizontalSlider_b, self.spinBox_b)
        MainWindow.setTabOrder(self.spinBox_b, self.dial_bright)
        MainWindow.setTabOrder(self.dial_bright, self.pushButton_last01)
        MainWindow.setTabOrder(self.pushButton_last01, self.pushButton_last02)
        MainWindow.setTabOrder(self.pushButton_last02, self.pushButton_last03)
        MainWindow.setTabOrder(self.pushButton_last03, self.pushButton_last04)
        MainWindow.setTabOrder(self.pushButton_last04, self.pushButton_last05)
        MainWindow.setTabOrder(self.pushButton_last05, self.pushButton_last06)
        MainWindow.setTabOrder(self.pushButton_last06, self.pushButton_last07)
        MainWindow.setTabOrder(self.pushButton_last07, self.pushButton_last08)
        MainWindow.setTabOrder(self.pushButton_last08, self.pushButton_last09)
        MainWindow.setTabOrder(self.pushButton_last09, self.pushButton_last10)
        MainWindow.setTabOrder(self.pushButton_last10, self.pushButton_last11)
        MainWindow.setTabOrder(self.pushButton_last11, self.pushButton_last12)
        MainWindow.setTabOrder(self.pushButton_last12, self.pushButton_last13)
        MainWindow.setTabOrder(self.pushButton_last13, self.pushButton_last14)
        MainWindow.setTabOrder(self.pushButton_last14, self.pushButton_last15)
        MainWindow.setTabOrder(self.pushButton_last15, self.pushButton_last16)
        MainWindow.setTabOrder(self.pushButton_last16, self.pushButton_last17)
        MainWindow.setTabOrder(self.pushButton_last17, self.pushButton_last18)
        MainWindow.setTabOrder(self.pushButton_last18, self.pushButton_last19)
        MainWindow.setTabOrder(self.pushButton_last19, self.pushButton_last20)
        MainWindow.setTabOrder(self.pushButton_last20, self.comboBox_effect1)
        MainWindow.setTabOrder(self.comboBox_effect1, self.spinBox_time1)
        MainWindow.setTabOrder(self.spinBox_time1, self.pushButton_effect1)
        MainWindow.setTabOrder(self.pushButton_effect1, self.plainTextEdit_input1)
        MainWindow.setTabOrder(self.plainTextEdit_input1, self.comboBox_effect2)
        MainWindow.setTabOrder(self.comboBox_effect2, self.spinBox_time2)
        MainWindow.setTabOrder(self.spinBox_time2, self.pushButton_effect2)
        MainWindow.setTabOrder(self.pushButton_effect2, self.plainTextEdit_input2)
        MainWindow.setTabOrder(self.plainTextEdit_input2, self.comboBox_effect3)
        MainWindow.setTabOrder(self.comboBox_effect3, self.spinBox_time3)
        MainWindow.setTabOrder(self.spinBox_time3, self.pushButton_effect3)
        MainWindow.setTabOrder(self.pushButton_effect3, self.plainTextEdit_input3)
        MainWindow.setTabOrder(self.plainTextEdit_input3, self.comboBox_effect4)
        MainWindow.setTabOrder(self.comboBox_effect4, self.spinBox_time4)
        MainWindow.setTabOrder(self.spinBox_time4, self.pushButton_effect4)
        MainWindow.setTabOrder(self.pushButton_effect4, self.plainTextEdit_input4)
        MainWindow.setTabOrder(self.plainTextEdit_input4, self.comboBox_device)
        MainWindow.setTabOrder(self.comboBox_device, self.pushButton_update)
        MainWindow.setTabOrder(self.pushButton_update, self.horizontalSlider_wb_r)
        MainWindow.setTabOrder(self.horizontalSlider_wb_r, self.spinBox_wb_r)
        MainWindow.setTabOrder(self.spinBox_wb_r, self.horizontalSlider_wb_g)
        MainWindow.setTabOrder(self.horizontalSlider_wb_g, self.spinBox_wb_g)
        MainWindow.setTabOrder(self.spinBox_wb_g, self.horizontalSlider_wb_b)
        MainWindow.setTabOrder(self.horizontalSlider_wb_b, self.spinBox_wb_b)
        MainWindow.setTabOrder(self.spinBox_wb_b, self.doubleSpinBox_gamma)
        MainWindow.setTabOrder(self.doubleSpinBox_gamma, self.graphicsView_gamma)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "P3DA"))
        self.groupBox_color_bright.setTitle(_translate("MainWindow", "Color and brightness"))
        self.label_2.setText(_translate("MainWindow", "Green"))
        self.label_3.setText(_translate("MainWindow", "Blue"))
        self.label.setText(_translate("MainWindow", "Red"))
        self.pushButton_color.setText(_translate("MainWindow", "#000000"))
        self.groupBox_last_colors.setTitle(_translate("MainWindow", "Last colors"))
        self.pushButton_last18.setText(_translate("MainWindow", "#999999"))
        self.pushButton_last11.setText(_translate("MainWindow", "#7f7f00"))
        self.pushButton_last15.setText(_translate("MainWindow", "#000000"))
        self.pushButton_last04.setText(_translate("MainWindow", "#ffff00"))
        self.pushButton_last17.setText(_translate("MainWindow", "#666666"))
        self.pushButton_last05.setText(_translate("MainWindow", "#ff00ff"))
        self.pushButton_last12.setText(_translate("MainWindow", "#7f007f"))
        self.pushButton_last08.setText(_translate("MainWindow", "#7f0000"))
        self.pushButton_last16.setText(_translate("MainWindow", "#333333"))
        self.pushButton_last07.setText(_translate("MainWindow", "#ffffff"))
        self.pushButton_last14.setText(_translate("MainWindow", "#7f7f7f"))
        self.pushButton_last20.setText(_translate("MainWindow", "#0369cf"))
        self.pushButton_last09.setText(_translate("MainWindow", "#007f00"))
        self.pushButton_last13.setText(_translate("MainWindow", "#007f7f"))
        self.pushButton_last10.setText(_translate("MainWindow", "#00007f"))
        self.pushButton_last02.setText(_translate("MainWindow", "#00ff00"))
        self.pushButton_last19.setText(_translate("MainWindow", "#cccccc"))
        self.pushButton_last03.setText(_translate("MainWindow", "#0000ff"))
        self.pushButton_last01.setText(_translate("MainWindow", "#ff0000"))
        self.pushButton_last06.setText(_translate("MainWindow", "#00ffff"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_light), _translate("MainWindow", "Light"))
        self.groupBox_effect2.setTitle(_translate("MainWindow", "Effect2"))
        self.plainTextEdit_input2.setPlainText(_translate("MainWindow", "#ffffff\n"
"#ffff00\n"
"#ff00ff\n"
"#ff0000\n"
"#00ffff\n"
"#00ff00\n"
"#000000"))
        self.label_16.setText(_translate("MainWindow", "ms"))
        self.label_11.setText(_translate("MainWindow", "Effect"))
        self.label_10.setText(_translate("MainWindow", "Time"))
        self.pushButton_effect2.setText(_translate("MainWindow", "On/off"))
        self.groupBox_effect3.setTitle(_translate("MainWindow", "Effect3"))
        self.label_17.setText(_translate("MainWindow", "ms"))
        self.label_13.setText(_translate("MainWindow", "Effect"))
        self.label_12.setText(_translate("MainWindow", "Time"))
        self.pushButton_effect3.setText(_translate("MainWindow", "On/off"))
        self.plainTextEdit_input3.setPlainText(_translate("MainWindow", "#ffffff\n"
"#ffff00\n"
"#ff00ff\n"
"#ff0000\n"
"#00ffff\n"
"#00ff00\n"
"#000000"))
        self.groupBox_effect4.setTitle(_translate("MainWindow", "Effect4"))
        self.plainTextEdit_input4.setPlainText(_translate("MainWindow", "#ffffff\n"
"#ffff00\n"
"#ff00ff\n"
"#ff0000\n"
"#00ffff\n"
"#00ff00\n"
"#000000"))
        self.label_18.setText(_translate("MainWindow", "ms"))
        self.label_14.setText(_translate("MainWindow", "Time"))
        self.label_15.setText(_translate("MainWindow", "Effect"))
        self.pushButton_effect4.setText(_translate("MainWindow", "On/off"))
        self.groupBox_effect1.setTitle(_translate("MainWindow", "Effect 1"))
        self.pushButton_effect1.setText(_translate("MainWindow", "On/off"))
        self.label_7.setText(_translate("MainWindow", "ms"))
        self.label_8.setText(_translate("MainWindow", "Time"))
        self.label_9.setText(_translate("MainWindow", "Effect"))
        self.plainTextEdit_input1.setPlainText(_translate("MainWindow", "#ffffff\n"
"#ffff00\n"
"#ff00ff\n"
"#ff0000\n"
"#00ffff\n"
"#00ff00\n"
"#000000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ilumination), _translate("MainWindow", "Ilumination"))
        self.label_23.setText(_translate("MainWindow", "I&nput"))
        self.pushButton_sound_onoff.setText(_translate("MainWindow", "On/off"))
        self.label_41.setText(_translate("MainWindow", "E&ffect"))
        self.groupBox_bit_detect.setTitle(_translate("MainWindow", "Bit detector"))
        self.plainTextEdit_bitdetector.setPlainText(_translate("MainWindow", "#ff0000\n"
"#00ff00\n"
"#0000ff"))
        self.groupBox_freq.setTitle(_translate("MainWindow", "Frequency"))
        self.pushButton_color_high.setText(_translate("MainWindow", "#0000ff"))
        self.pushButton_color_low.setText(_translate("MainWindow", "#ff0000"))
        self.pushButton_color_mid.setText(_translate("MainWindow", "#00ff00"))
        self.label_22.setText(_translate("MainWindow", "Low"))
        self.label_24.setText(_translate("MainWindow", "Middle"))
        self.label_25.setText(_translate("MainWindow", "High"))
        self.label_26.setText(_translate("MainWindow", "Color"))
        self.label_42.setText(_translate("MainWindow", "Multiplier"))
        self.label_45.setText(_translate("MainWindow", "Noise"))
        self.label_43.setText(_translate("MainWindow", "Limits"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sound), _translate("MainWindow", "Sound"))
        self.groupBox_setup_ext.setTitle(_translate("MainWindow", "Setup"))
        self.pushButton_zones.setText(_translate("MainWindow", "Set zones"))
        self.label_38.setText(_translate("MainWindow", "E&ffect"))
        self.label_36.setText(_translate("MainWindow", "&Update interval"))
        self.label_39.setText(_translate("MainWindow", "Effe&ct time"))
        self.spinBox_effect.setSuffix(_translate("MainWindow", " ms"))
        self.spinBox_update.setSuffix(_translate("MainWindow", " ms"))
        self.label_4.setText(_translate("MainWindow", "Count of zones"))
        self.pushButton_ext_on_off.setText(_translate("MainWindow", "On/off"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ext_backlight), _translate("MainWindow", "Ext. backlight"))
        self.groupBox_wb.setTitle(_translate("MainWindow", "White balance"))
        self.label_20.setText(_translate("MainWindow", "Red"))
        self.label_19.setText(_translate("MainWindow", "Green"))
        self.label_21.setText(_translate("MainWindow", "Blue"))
        self.groupBox_gamma.setTitle(_translate("MainWindow", "Gamma"))
        self.groupBox_device.setTitle(_translate("MainWindow", "Device selector"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setup), _translate("MainWindow", "Setup"))

from pyqtgraph import PlotWidget
